services:
  svelte-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "preview", "--", "--host", "0.0.0.0" , "--port", "3000"]